<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Multinomial Logit Model (MNL)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/readable.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 66px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 71px;
  margin-top: -71px;
}

.section h2 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h3 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h4 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h5 {
  padding-top: 71px;
  margin-top: -71px;
}
.section h6 {
  padding-top: 71px;
  margin-top: -71px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="statedpref.html">Stated Preference Survey</a>
</li>
<li>
  <a href="MNL.html">MNL</a>
</li>
<li>
  <a href="apps.html">Interactive R</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Multinomial Logit Model (MNL)</h1>

</div>


<hr>
<p><br></br></p>
<div id="introduction" class="section level2">
<h2>1 Introduction</h2>
<p>This document elaborates on the steps done to run Multinomial Logistic Regression on the results of the <a href="statedpref.html">Stated Preference Survey</a>. Multinomial Logistic Regression serves to predict an individual’s mode choice (public bus, shared bicycles/PMDs, or Dalphin) using inputs such as the individual’s demographics, mode specific variables and non-mode specific variables.</p>
<p><br></br></p>
</div>
<div id="the-data" class="section level2">
<h2>2 The Data</h2>
<p>First, we read in the data from the stated preference survey which is in the CSV format (Comma Separated Values).</p>
<pre class="r"><code>modechoice &lt;- read.csv(&quot;ModeChoice.csv&quot;)</code></pre>
<p>Looking at the structure of the dataset <code>str()</code>, it contains 1000 observations of 40 variables.</p>
<pre class="r"><code>str(modechoice)</code></pre>
<p><br></br></p>
<hr>
</div>
<div id="predicting-na-incomes-with-linear-regression" class="section level2">
<h2>3 Predicting “NA” Incomes with Linear Regression</h2>
<p>Some of the entries in the <code>Income</code> column are <code>NA</code>. To fill this missing information, we used linear regression to predict their values.</p>
<p>We separate the dataset into two: one with stated incomes, and another which have <code>NA</code> for <code>Income</code>.</p>
<pre class="r"><code>incomenotNA &lt;- subset(modechoice, modechoice$Income != &quot;NA&quot;)
incomeNA &lt;- subset(modechoice,is.na(modechoice$Income))</code></pre>
<p>There are 752 observations with stated incomes and 248 observations where income is <code>NA</code>.</p>
<p><br></br></p>
<div id="creating-training-and-test-sets" class="section level4">
<h4>3.1 Creating Training and Test Sets</h4>
<p>We now create training and test sets from the observations where incomes are stated (<code>incomenotNA</code>). The <code>caTools</code> package is used.</p>
<pre class="r"><code>library(caTools)</code></pre>
<p>We set the random seed so that the results will be replicable. The training and test sets are obtained with a 65/35 split ratio.</p>
<pre class="r"><code>set.seed(1)
split &lt;- sample.split(incomenotNA$Age, SplitRatio = 0.65)

incometraining &lt;- subset(incomenotNA,split==TRUE)
incometest &lt;- subset(incomenotNA,split==FALSE)</code></pre>
<p><br></br></p>
</div>
<div id="creating-a-linear-regression-model" class="section level4">
<h4>3.2 Creating a Linear Regression Model</h4>
<p>We now create a linear regression. The first model includes all demographic information of the individual:</p>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>Age</code></td>
<td align="left">The individual’s age group</td>
</tr>
<tr class="even">
<td align="left"><code>Gender</code></td>
<td align="left">The individual’s gender</td>
</tr>
<tr class="odd">
<td align="left"><code>HouseholdType</code></td>
<td align="left">Household type</td>
</tr>
<tr class="even">
<td align="left"><code>HouseholdSize</code></td>
<td align="left">Number of people in the household</td>
</tr>
<tr class="odd">
<td align="left"><code>Residential</code></td>
<td align="left">Residential location of the household</td>
</tr>
<tr class="even">
<td align="left"><code>Cars</code></td>
<td align="left">The number of cars in the household</td>
</tr>
<tr class="odd">
<td align="left"><code>Concession</code></td>
<td align="left">The type of concession pass, if any</td>
</tr>
</tbody>
</table>
<pre class="r"><code>income.model1 &lt;- lm(Income ~ Age + Gender + HouseholdType + 
                      HouseholdSize + Residential + Cars + 
                      Concession,
                    data = incometraining)

summary(income.model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Income ~ Age + Gender + HouseholdType + HouseholdSize + 
##     Residential + Cars + Concession, data = incometraining)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4952 -0.9929 -0.1726  0.9612  2.9008 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    0.531995   0.484056   1.099 0.272303    
## Age            0.797357   0.048075  16.586  &lt; 2e-16 ***
## Gender        -0.360214   0.122404  -2.943 0.003410 ** 
## HouseholdType  0.011665   0.045024   0.259 0.795689    
## HouseholdSize -0.293817   0.077210  -3.805 0.000160 ***
## Residential    0.003033   0.009273   0.327 0.743766    
## Cars           0.354159   0.101643   3.484 0.000539 ***
## Concession     0.145744   0.079579   1.831 0.067655 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.317 on 480 degrees of freedom
## Multiple R-squared:  0.4055, Adjusted R-squared:  0.3968 
## F-statistic: 46.77 on 7 and 480 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The model has an adjusted <span class="math inline">\(R^2\)</span> value of 0.39682. <code>HouseholdType</code> and <code>Residential</code> are not significant at the 90% significance level.</p>
<p><br></br></p>
</div>
<div id="removing-householdtype-and-residential" class="section level4">
<h4>3.3 Removing <code>HouseholdType</code> and <code>Residential</code></h4>
<p>We remove the insignificant variables from the model.</p>
<pre class="r"><code>income.model2 &lt;- lm(Income ~ Age + Gender +HouseholdSize + Cars + Concession,
                    data=incometraining)

summary(income.model2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Income ~ Age + Gender + HouseholdSize + Cars + Concession, 
##     data = incometraining)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.5561 -0.9873 -0.1662  0.9926  2.9186 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    0.64785    0.35692   1.815 0.070124 .  
## Age            0.79474    0.04702  16.901  &lt; 2e-16 ***
## Gender        -0.35916    0.12124  -2.962 0.003205 ** 
## HouseholdSize -0.30061    0.07509  -4.004 7.22e-05 ***
## Cars           0.36404    0.09577   3.801 0.000163 ***
## Concession     0.15273    0.07716   1.979 0.048336 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.315 on 482 degrees of freedom
## Multiple R-squared:  0.4053, Adjusted R-squared:  0.3991 
## F-statistic: 65.69 on 5 and 482 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This model has an increased adjusted <span class="math inline">\(R^2\)</span> value of 0.39911. <code>Concession</code> and <code>(Intercept)</code> are the least significant variables.</p>
<p><br></br></p>
</div>
<div id="variable-selection" class="section level4">
<h4>3.4 Variable Selection</h4>
<p>Several other combinations of variables were tested. The combination of variables which gave the highest adjusted <span class="math inline">\(R^2\)</span> was chosen.</p>
<table style="width:90%;">
<colgroup>
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Model</th>
<th align="center"><code>Age</code></th>
<th align="center"><code>Gender</code></th>
<th align="center"><code>HouseholdType</code></th>
<th align="center"><code>HouseholdSize</code></th>
<th align="center"><code>Residential</code></th>
<th align="center"><code>Cars</code></th>
<th align="center"><code>Concession</code></th>
<th align="left">Adjusted <span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">0.39682</td>
</tr>
<tr class="even">
<td align="center"><strong>2</strong></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left"><strong>0.39911</strong></td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="left">0.39548</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">0.39794</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">0.39799</td>
</tr>
</tbody>
</table>
<p>Model 2 has the highest adjusted <span class="math inline">\(R^2\)</span>. We now evaluate this model on the test set by calculating the test <span class="math inline">\(R^2\)</span>. This is given by the formula:</p>
<p><span class="math display">\[R^2 = 1 - \frac{SSE}{SST}\]</span></p>
<p>where <span class="math inline">\(SSE\)</span> is the Sum of Squared Errors and <span class="math inline">\(SST\)</span> is the Sum of Squared Errors (Total).</p>
<pre class="r"><code>incomeprediction &lt;- predict(income.model2, newdata=incometest)
sse &lt;- sum((incomeprediction-incometest$Income)^2)
sst &lt;- sum((incometest$Income-mean(incometraining$Income))^2)</code></pre>
<p>The test <span class="math inline">\(R^2\)</span> for model 2 is 0.37408. We now use model 2 to predict the <code>NA</code> entries in the dataset.</p>
<pre class="r"><code>NAincomeprediction &lt;- predict(income.model2, newdata=incomeNA) 

modechoice$Income &lt;- ifelse(is.na(modechoice$Income),
                            NAincomeprediction,
                            modechoice$Income)</code></pre>
<p><br></br></p>
<hr>
</div>
</div>
<div id="fitting-the-mnl-model" class="section level2">
<h2>4 Fitting the MNL model</h2>
<p>Now that all entries in the dataset have no <code>NA</code> values, we can proceed to conduct Multinomial Logistic Regression.</p>
<p><br></br></p>
<div id="generating-training-and-test-sets" class="section level4">
<h4>4.1 Generating Training and Test Sets</h4>
<p>Each row in the dataset corresponds to a choice task of a particular individual. We want to randomly split the individuals into the training or test set, while keeping all 8 choice tasks intact.</p>
<pre class="r"><code>set.seed(0)
mask = rep(x = sample.split(rep(1, 125), SplitRatio = 0.7),
           each = 8)
modechoice.training = subset(modechoice, mask==TRUE)
modechoice.test = subset(modechoice, mask==FALSE)</code></pre>
<p>The table below shows the first 16 rows of the training set. All 8 choice tasks of an individual are preserved. <code>Case</code> refers to the individual, while <code>Task</code> refers to the choice task.</p>
<pre class="r"><code>kable(modechoice.training[1:16,2:6])</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Case</th>
<th align="right">Task</th>
<th align="right">weather1</th>
<th align="right">weather2</th>
<th align="right">weather3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>10</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>11</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>12</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>13</td>
<td align="right">2</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td>14</td>
<td align="right">2</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td>15</td>
<td align="right">2</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td>16</td>
<td align="right">2</td>
<td align="right">8</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td>17</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>18</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>19</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>20</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>21</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td>22</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="odd">
<td>23</td>
<td align="right">3</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td>24</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<p><br></br></p>
</div>
<div id="creating-an-mlogit-object" class="section level4">
<h4>4.2 Creating an <code>mlogit()</code> Object</h4>
<p>We use the <code>mlogit</code> package which will help us conduct Multinomial Logistic Regression.</p>
<pre class="r"><code>library(mlogit)</code></pre>
<pre class="r"><code>S &lt;- mlogit.data(modechoice.training,
                 shape=&quot;wide&quot;,
                 choice=&quot;A&quot;,
                 varying=c(4:18),
                 sep=&quot;&quot;,
                 alt.levels=c(&quot;A.bus&quot;,&quot;A.cyclingPMD&quot;,&quot;A.dalphin&quot;),
                 id.var=&quot;Case&quot;)</code></pre>
<p><br></br></p>
</div>
<div id="calculating-aic" class="section level4">
<h4>4.3 Calculating AIC</h4>
<p>The Akaike Information Criterion (AIC) is…. a lower AIC value is better. The formula is given by:</p>
<p><span class="math display">\[AIC = -2 LL(\hat\beta) + 2|\hat\beta|\]</span></p>
<p>where <span class="math inline">\(LL(\hat\beta)\)</span> is the Log-likelihood of the estimated model and <span class="math inline">\(|\hat\beta|\)</span> is the number of coefficients to be estimated (including the intercept).</p>
<p>For convenience, we define a function <code>calc.AIC()</code> that takes in a model and returns its AIC value.</p>
<pre class="r"><code>calc.AIC &lt;- function (model) {
  return(-2*model$logLik[1] + 2*length(model$coefficients))
}</code></pre>
<p><br></br></p>
</div>
<div id="variable-selection-1" class="section level4">
<h4>4.4 Variable Selection</h4>
<table>
<colgroup>
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Model</th>
<th align="center"><code>weather</code></th>
<th align="center"><code>fare</code></th>
<th align="center"><code>wait</code></th>
<th align="center"><code>ivtt</code></th>
<th align="center"><code>access</code></th>
<th align="center"><code>Age</code></th>
<th align="center"><code>Gender</code></th>
<th align="center"><code>Income</code></th>
<th align="center"><code>HouseholdType</code></th>
<th align="center"><code>HouseholdSize</code></th>
<th align="center"><code>Residential</code></th>
<th align="center"><code>Cars</code></th>
<th align="center"><code>Concession</code></th>
<th align="left">AIC Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1357.116</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1333.944</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1334.169</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1335.254</td>
</tr>
</tbody>
</table>
<p>Model 2 the better model as it has the lowest AIC. We now build upon Model 2 by including individual-specific attributes.</p>
<table>
<colgroup>
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Model</th>
<th align="center"><code>weather</code></th>
<th align="center"><code>fare</code></th>
<th align="center"><code>wait</code></th>
<th align="center"><code>ivtt</code></th>
<th align="center"><code>access</code></th>
<th align="center"><code>Age</code></th>
<th align="center"><code>Gender</code></th>
<th align="center"><code>Income</code></th>
<th align="center"><code>HouseholdType</code></th>
<th align="center"><code>HouseholdSize</code></th>
<th align="center"><code>Residential</code></th>
<th align="center"><code>Cars</code></th>
<th align="center"><code>Concession</code></th>
<th align="left">AIC Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">5</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1326.97</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1328.847</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1320.019</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1323.093</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1328.914</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1324.68</td>
</tr>
<tr class="odd">
<td align="center">12</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="left">1319.543</td>
</tr>
<tr class="even">
<td align="center">13</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">1318.999</td>
</tr>
</tbody>
</table>
<p>Now we try adding the other mode-specific variables that we removed just now.</p>
<table>
<colgroup>
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Model</th>
<th align="center"><code>weather</code></th>
<th align="center"><code>fare</code></th>
<th align="center"><code>wait</code></th>
<th align="center"><code>ivtt</code></th>
<th align="center"><code>access</code></th>
<th align="center"><code>Age</code></th>
<th align="center"><code>Gender</code></th>
<th align="center"><code>Income</code></th>
<th align="center"><code>HouseholdType</code></th>
<th align="center"><code>HouseholdSize</code></th>
<th align="center"><code>Residential</code></th>
<th align="center"><code>Cars</code></th>
<th align="center"><code>Concession</code></th>
<th align="left">AIC Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">14</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">1319.172</td>
</tr>
<tr class="even">
<td align="center">15</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">1320.237</td>
</tr>
<tr class="odd">
<td align="center">16</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="left">1320.235</td>
</tr>
</tbody>
</table>
<p>Model 11 is the best as it has the lowest AIC and highest proportion of significant coefficients. Now we build upon Model 4 by including individual-specific attributes.</p>
<table>
<colgroup>
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="5%" />
<col width="8%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Model</th>
<th align="center"><code>weather</code></th>
<th align="center"><code>fare</code></th>
<th align="center"><code>wait</code></th>
<th align="center"><code>ivtt</code></th>
<th align="center"><code>access</code></th>
<th align="center"><code>Age</code></th>
<th align="center"><code>Gender</code></th>
<th align="center"><code>Income</code></th>
<th align="center"><code>HouseholdType</code></th>
<th align="center"><code>HouseholdSize</code></th>
<th align="center"><code>Residential</code></th>
<th align="center"><code>Cars</code></th>
<th align="center"><code>Concession</code></th>
<th align="left">AIC Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">17</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1328.258</td>
</tr>
<tr class="even">
<td align="center">18</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1330.134</td>
</tr>
<tr class="odd">
<td align="center">19</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1322.806</td>
</tr>
<tr class="even">
<td align="center">20</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1325.969</td>
</tr>
<tr class="odd">
<td align="center">21</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1332.142</td>
</tr>
<tr class="even">
<td align="center">22</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
<td align="left">1311.476</td>
</tr>
<tr class="odd">
<td align="center">23</td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="center"></td>
<td align="center"><span class="math inline">\(\checkmark\)</span></td>
<td align="center"></td>
<td align="left">1308.912</td>
</tr>
</tbody>
</table>
<p>Overall, Model 23 is the best model with the lowest AIC value.</p>
<p><br></br></p>
</div>
<div id="predicting-mode-choice" class="section level4">
<h4>4.5 Predicting Mode Choice</h4>
<p>We use the <code>predict()</code> function to give the probability of an individual choosing a particular mode.</p>
<pre class="r"><code>P &lt;- predict(M23, newdata = S, type = &quot;response&quot;)</code></pre>
<p>Looking at the first three rows of the dataset:</p>
<pre class="r"><code>kable(P[1:3,], align = &#39;c&#39;)</code></pre>
<table>
<thead>
<tr class="header">
<th align="center">Bus</th>
<th align="center">Shared Bicycles/PMDs</th>
<th align="center">Dalphin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0.278</td>
<td align="center">0.614</td>
<td align="center">0.108</td>
</tr>
<tr class="even">
<td align="center">0.265</td>
<td align="center">0.584</td>
<td align="center">0.151</td>
</tr>
<tr class="odd">
<td align="center">0.232</td>
<td align="center">0.511</td>
<td align="center">0.257</td>
</tr>
</tbody>
</table>
<p>For example, the individual corresponding to the first row will choose the bus with a 27.8% chance, Shared Bicycles/PMDs with a 61.4% chance, and the Dalphin with a 10.8% chance.</p>
<p>We let the predicted choice to be the most likely alternative (highest chance of being chosen).</p>
<pre class="r"><code>PredictedChoice &lt;- apply(P, 1, which.max)</code></pre>
<p>Using a confusion matrix, we compare the actual choice in the training set with the predicted choice by the model.</p>
<pre class="r"><code>ActualChoice &lt;- modechoice.training$A</code></pre>
<p><strong>Predicted Choice vs. Actual Choice</strong></p>
<pre class="r"><code>kable(table(PredictedChoice, ActualChoice))</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">Bus</th>
<th align="right">Shared Bicycles/PMDs</th>
<th align="right">Dalphin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bus</td>
<td align="right">68</td>
<td align="right">19</td>
<td align="right">46</td>
</tr>
<tr class="even">
<td>Shared Bicycles/PMDs</td>
<td align="right">26</td>
<td align="right">42</td>
<td align="right">17</td>
</tr>
<tr class="odd">
<td>Dalphin</td>
<td align="right">132</td>
<td align="right">64</td>
<td align="right">282</td>
</tr>
</tbody>
</table>
<p>The diagonal entries of the confusion matrix are the instances where the model correctly predicts the actual choice of the individual. Accuracy is calculated by finding the proportion of instances where the model correctly predicted the actual choice. This model has an accuracy of 56.32%.</p>
<p><br></br></p>
<hr>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
